<?php
$titles = array("Secretaria", "Divisão", "Fabricante Modelo", "Tipo", "P.Livre", "Cota L", "Ab .  Mês atual", "Ab media", "Codigo", "Placa");
foreach ($titles as $title) {
    echo mb_convert_encoding($title, "ISO-8859-1") . ";"; 
}
echo "\n";

foreach ($carros as $carro) { 
    
    $row = array( $carro['secretariaNome'], $carro['divisaoNome'], 
        $carro['fabricanteNome'] . $carro['modeloNome'], $carro['carroTipo'], 
        $carro['carroPasseLivre'] == 1 ?  "&bull;"  : "" , $carro['carroCota'], 
        $carro['carroAbMesAtual'], $carro['carroAbMediaKmLt'], 
        $carro['carroCodigo'], $carro['carroPlaca'] );
    
    foreach ($row as $cel) {
        echo Csv::prepareData($cel) . ";"; 
    }    
    echo "\n";
} 
    

/*  echo $carro['secretariaNome']?>;<?php echo $carro['divisaoNome']?>;<?php echo $carro['fabricanteNome']?> / <?php echo $carro['modeloNome'], $carro['carroTipo']", "$carro['carroPasseLivre'] == 1 ?  "&bull;"  : "" ", "$carro['carroCota']", "$carro['carroAbMesAtual']", "$carro['carroAbMediaKmLt']", "$carro['carroCodigo']", "$carro['carroPlaca']?>;
 */
  


