<link href="css/carro/index.css" rel="stylesheet" type="text/css"/>
<script src="js/carro/index.js" type="text/javascript"></script>

<h1 class="titulo1">Veículos</h1>

<nav id="menu2" class="menu1">
    <ul>
        <li><div class="fa-th" title="Exportar para planilha" 
        onclick="location='<?php echo BASE_URL?>carro/exportarCsv/queryKey/<?php echo $lastQueryKey?>'"></div></li> 
                 
        <li><div class="fa-print" title="Imprimir" 
        onclick="location='<?php echo BASE_URL?>carro/exportarImpressao/queryKey/<?php echo $lastQueryKey?>'"></div></li>         
        
        <li><div class="fa-glass" title="Filtrar resultados" 
            onclick=""></div></li>         
    </ul>    
</nav>

<input id="currentPg" type="hidden" value="<?php echo $paginator->pgCurrent ?>"/>

<div id="filter-content" class="clear box1">
    <form id="carFormFilter" class="" action="" method="post">
        <div class="form-item">
            <label>Período</label>
            <input id="dateFrom" type="text" value="<?php echo $dateFrom?>" placeholder="Data de" oninput="data.maskData(this)"/>
            <input id="dateTo" type="text" value="<?php echo $dateTo?>" placeholder="Data até"  oninput="data.maskData(this)"/>
        </div>
        <div class="form-item">
            <label>&nbsp;</label>
            <input type="submit" value="OK"/>            
        </div>
    </form>
</div>

<div id="info-box">
    <strong>Num. registros: </strong> <?php echo $totNumRows?>
</div>

<div class="paginator clear">
    <?php for($p=0; $p<=$paginator->nPg; $p++){
        $class = $p == $paginator->pgCurrent ? 'sel' : '';
        ?><a class="<?php echo $class?> pgButton" data-pg="<?php echo $p?>" ><?php echo $p+1?></a><?php }?>
</div>  

<table id="carros" class="tabela2">
    <tr>
        <th>Secretaria</th>
        <th>Divisão</th>
        <th>Fabricante Modelo</th>
        <th>Tipo</th>
        <th>P.Livre</th>
        <th>Cota L</th>
        <th>Ab. Mês atual</th>
        <th>Ab. media</th>
        <th>Codigo</th>
        <th>Placa</th>
    </tr>
    <?php foreach ($carros as $carro) { ?>
    <tr>
        <td><?php echo $carro['secretariaNome']?></td>
        <td><?php echo $carro['divisaoNome']?></td>
        <td><?php echo $carro['fabricanteNome']?> / <?php echo $carro['modeloNome']?></td>
        <td><?php echo $carro['carroTipo']?></td>
        <td><?php echo $carro['carroPasseLivre'] == 1 ? "&bull;" : ""?></td>  
        <td><?php echo $carro['carroCota']?></td>  
        <td><?php echo $carro['carroAbMesAtual']?></td>  
        <td><?php echo $carro['carroAbMediaKmLt']?></td>  
        <td><?php echo $carro['carroCodigo']?></td>
        <td><?php echo $carro['carroPlaca']?></td>
    </tr>
    <?php } ?>
</table>

<div class="paginator">
    <?php for($p=0; $p<=$paginator->nPg; $p++){
        $class = $p == $paginator->pgCurrent ? 'sel' : '';
        ?><a class="<?php echo $class?>" href="carro/index/pg/<?php echo $p?>"><?php echo $p+1?></a><?php }?>
</div>    
