<link href="css/carro/editar.css" rel="stylesheet" type="text/css"/>
<script src="js/carro/editar.js" type="text/javascript"></script>

<link href="ui/ui-lightness/jquery-ui.theme.css" rel="stylesheet" type="text/css"/>
<link href="ui/ui-lightness/jquery-ui.css" rel="stylesheet" type="text/css"/>

<script src="ui/jquery-ui.min.js" type="text/javascript"></script>


<script src="ui/datepickerBR.js" type="text/javascript"></script>

<h1 class="titulo1">Veículo</h1>

<section>
    
    <form id="editarForm" class="form1" action="carro/gravar" method="post">

        <input id="id" name="id" type="hidden" value="<?php echo isset($carro['id']) ? $carro['id'] : 0?>"/>
        <input id="secretariaForcar" type="hidden" value="<?php echo isset($secretariaForcar) ? $secretariaForcar : 0?>"/>
        
        <div class="form-item">
            <div class="nome">Data de cadastro</div>
            <input id="data" class="data" type="text" 
                   value="<?php echo isset($carro['created_at']) ? Date::toBr($carro['created_at']) : date("d-m-Y")?>"/>
        </div>    

        <div class="form-item">
            <label>Secretaria-</label>
            <select id="idS" name="idS" required="">
                <option></option>
                <?php foreach ($secretarias as $secretaria):?>
                    <option value="<?php echo $secretaria['id']?>" 
                        <?php echo isset($carro['idS']) && $carro['idS'] == $secretaria['id'] ? "selected=''" : ""?> >
                        <?php echo $secretaria['nome']?>
                    </option>
                <?php endforeach;?>
            </select>        
        </div>

        <div class="form-item">
            <label>Divisão</label>
            <select name="idD" required="">
                <option></option>
                <?php foreach ($divisoes as $divisao):?>
                    <option value="<?php echo $divisao['id']?>" 
                        <?php echo isset($carro['idD']) && $carro['idD'] == $divisao['id'] ? "selected=''" : ""?> >
                        <?php echo $divisao['nome']?>
                    </option>
                <?php endforeach;?>
            </select>        
        </div>

        <div class="form-item">
            <label>Fabricante</label>
            <select name="idF" required="">
                <option></option>
                <?php foreach ($fabricantes as $fabricante):?>
                    <option value="<?php echo $fabricante['id']?>" 
                        <?php echo isset($carro['idF']) && $carro['idF'] == $fabricante['id'] ? "selected=''" : ""?> >
                        <?php echo $fabricante['nome']?>
                    </option>
                <?php endforeach;?>
            </select>        
        </div>

        <div class="form-item">
            <label>Modelo</label>
            <select name="idM" required="">
                <option></option>
                <?php foreach ($modelos as $modelo):?>
                    <option value="<?php echo $modelo['id']?>" 
                        <?php echo isset($carro['idM']) && $carro['idM'] == $modelo['id'] ? "selected=''" : ""?> >
                        <?php echo $modelo['nome']?>
                    </option>
                <?php endforeach;?>
            </select>        
        </div>

        <div class="form-item">
            <label>Combustíveis autorizados</label>
            <?php foreach ($combustiveis as $combustivel):?>

                <input type="checkbox" name="idCo" value="<?php echo $combustivel['id']?>"
                       <?php echo isset($carro['idCo']) && $carro['idCo'] == $combustivel['id'] ? "checked=''" : ""?>
                       /><?php echo $combustivel['nome']?>

            <?php endforeach;?>
        </div>

        <div class="form-item">
            <label>Combustível</label>

            <select name="combustivel" required="">
                <option value=""></option>

                <option value="Flex" 
                    <?php echo isset($carro['combustivel']) && $carro['combustivel'] === "Flex" 
                    ? "selected=''" : ""?> >Flex</option>

                <option value="Diesel" 
                    <?php echo isset($carro['combustivel']) && $carro['combustivel'] === "Diesel" 
                    ? "selected=''" : ""?> >Diesel</option>

                <option value="Etanol" 
                    <?php echo isset($carro['combustivel']) && $carro['combustivel'] === "Etanol" 
                    ? "selected=''" : ""?> >Etanol</option>

                <option value="Gasolina" 
                    <?php echo isset($carro['combustivel']) && $carro['combustivel'] === "Gasolina" 
                    ? "selected=''" : ""?> >Gasolina</option>

            </select>

        </div>      

        <div class="form-item">
            <label>Cota mensal(Litros)</label>
            <input type="number" 
                   name="cota"
                   value="<?php echo isset($carro['cota']) ? $carro['cota'] : 0?>"/>
        </div>

        <div class="form-item">
            <label>Placa</label>
            <input type="text" 
                   name="placa"
                   value="<?php echo isset($carro['placa']) ? $carro['placa'] : ''?>"
                   pattern="[A-Za-z]{3} [0-9]{4}"
                   placeholder="ABC 1234"
                   />
        </div>

        <div class="form-item">
            <label>Tag</label>
            <input type="text" 
                   name="tag"
                   value="<?php echo isset($carro['tag']) ? $carro['tag'] : ''?>"               
                   />
        </div>

        <div class="form-item">
            <label>Vencimento extintor</label>
            <select name='extintor_venc'>
                <option></option>
                <?php
                $anoAt = date("Y", time());
                $anoFut = $anoAt + 10;
                for($ano=$anoAt; $ano<=$anoFut; $ano++){
                    for($i=1; $i<=2; $i++){
                        $anoSem = $ano.$i;
                        ?>
                        <option value="<?php echo $anoSem?>" <?php echo $carro['extintor_venc'] == $anoSem ? "selected=''" : ""?> ><?php echo $i?>º semestre - <?php echo $ano?></option>
                        <?php
                    }
                }
                ?>
            </select>
        </div>

        <div class="form-item">
            <label>Renavan</label>
            <input type="text" 
                   name="renavan"
                   value="<?php echo isset($carro['renavan']) ? $carro['renavan'] : ''?>"               
                   />
        </div>

        <div class="form-item">
            <label>Ano fabricação</label>
            <input type="number" 
                   name="anofab"
                   maxlength="4"
                   value="<?php echo isset($carro['anofab']) ? $carro['anofab'] : ''?>"               
                   />
        </div>

        <div class="form-item">
            <label>Ano modelo</label>
            <input type="number" 
                   name="anomod"
                   maxlength="4"
                   value="<?php echo isset($carro['anomod']) ? $carro['anomod'] : ''?>"               
                   />
        </div>

        <div class="form-item">
            <label>Nº chassi</label>
            <input type="text" 
                   name="chassi"
                   value="<?php echo isset($carro['chassi']) ? $carro['chassi'] : ''?>"               
                   />
        </div>

        <div class="form-item">
            <label>Cor predominante</label>
            <input type="text" 
                   name="cor"
                   value="<?php echo isset($carro['cor']) ? $carro['cor'] : ''?>"               
                   />
        </div>

        <div class="form-item">
            <label>Patrimônio</label>
            <input type="text" 
                   name="patrimonio"
                   value="<?php echo isset($carro['patrimonio']) ? $carro['patrimonio'] : ''?>"               
                   />
        </div>

        <div class="form-item">
            <label>Nº contrato</label>
            <input type="text" 
                   name="ncontrato"
                   value="<?php echo isset($carro['ncontrato']) ? $carro['ncontrato'] : ''?>"               
                   />
        </div>

        <div class="form-item">
            <label>Capacidade</label>
            <input type="number" 
                   name="capacidade"
                   value="<?php echo isset($carro['capacidade']) ? $carro['capacidade'] : 0?>"               
                   />
        </div>

        <div class="form-item">
            <label>Cilindrada</label>
            <input type="number" 
                   name="cilindrada"
                   value="<?php echo isset($carro['cilindrada']) ? $carro['cilindrada'] : 0?>"               
                   />
        </div>

        <div class="form-item">
            <label>Tipo</label>
            <select name="tipo" required="">
                <option value=""></option>
                <option value="PROPRIO" <?php echo $carro['tipo'] == 'PROPRIO' ? "selected=''" : ""?> >PROPRIO</option>
                <option value="ALUGADO" <?php echo $carro['tipo'] == 'ALUGADO' ? "selected=''" : ""?>>ALUGADO</option>
            </select>
        </div>

        <div class="form-item">
            <label>Restrição</label>
            <input name="passe_livre" type="hidden" value="0"/>
            <input name="passe_livre" type="checkbox" value="1" <?php echo $carro['passe_livre'] == '1' ? "checked=''" : ""?> />Passe livre (nunca impede o abastecimento).
        </div>

        <!-- outras tabelas inicio -->

        <div class="form-item">
            <label>KM inicial</label>
            <input type="number" 
                   name="kmIni"
                   readonly=""
                   value="<?php echo isset($primeiraKm) ? $primeiraKm : ''?>"               
                   />
        </div>

        <div class="form-item">
            <label>KM atual(último abastecimento)</label>
            <input type="number" 
                   name="kmAtu"
                   readonly=""
                   value="<?php echo isset($ultimaKm) ? $ultimaKm : ''?>"               
                   />
        </div>

        <div class="form-item">
            <label>Vincular a novo código</label>        
            <select name="cod">
                <option></option>
                <?php foreach ($codigos as $codigo) { ?>
                    <option><?php echo $codigo['cod']?></option>           
                <?php } ?>   
            </select>        
        </div>
        
        <!-- outras tabelas fim -->

        <div class="form-item clear">
            <input type="submit" value="Gravar"/>
        </div>

    </form>

</section>

<section>
    <label>Código</label>
    <div id='codBarras'>
        <img src="<?php echo $urlCodigoAtivo?>" alt="<?php echo $urlCodigoAtivo?>"/>
        <div><?php echo $codigoAtivo?></div>
    </div>
</section>