<table id="carros" class="tabela2">
    <tr>
        <th>Secretaria</th>
        <th>Divisão</th>
        <th>Fabricante Modelo</th>
        <th>Tipo</th>
        <th>P.Livre</th>
        <th>Cota L</th>
        <th>Ab. Mês atual</th>
        <th>Ab. media</th>
        <th>Codigo</th>
        <th>Placa</th>
    </tr>
    <?php foreach ($carros as $carro) { ?>
    <tr>
        <td><?php echo $carro['secretariaNome']?></td>
        <td><?php echo $carro['divisaoNome']?></td>
        <td><?php echo $carro['fabricanteNome']?> / <?php echo $carro['modeloNome']?></td>
        <td><?php echo $carro['carroTipo']?></td>
        <td><?php echo $carro['carroPasseLivre'] == 1 ? "&bull;" : ""?></td>  
        <td><?php echo $carro['carroCota']?></td>  
        <td><?php echo $carro['carroAbMesAtual']?></td>  
        <td><?php echo $carro['carroAbMediaKmLt']?></td>  
        <td><?php echo $carro['carroCodigo']?></td>
        <td><?php echo $carro['carroPlaca']?></td>
    </tr>
    <?php } ?>
</table>

<?php if(isset($imprimir)){?>
    <script>
        window.print();
        history.go(-1);
    </script>
<?php } ?>
