<link href="css/carro/index.css" rel="stylesheet" type="text/css"/>
<script src="js/carro/index.js" type="text/javascript"></script>

<h1 class="titulo1">Veículos</h1>

<nav id="menu2" class="menu1">
    <ul>
        <li><div class="fa-th" title="Exportar para planilha" 
        onclick="location='<?php echo BASE_URL?>carro/exportarCsv/queryKey/<?php echo $lastQueryKey?>'"></div></li> 
                 
        <li><div class="fa-print" title="Imprimir" 
        onclick="location='<?php echo BASE_URL?>carro/exportarImpressao/queryKey/<?php echo $lastQueryKey?>'"></div></li>         
        
        <li><div id="btFilter" class="fa-glass" title="Filtrar resultados" 
            onclick=""></div></li> 
            
        <li><div id="btFilter" class="fa-plus-square-o" title="Cadastrar novo" 
            onclick="location='carro/editar'"></div></li>      
    </ul>    
</nav>

<input id="currentPg" type="hidden" value="<?php echo $paginator->pgCurrent ?>"/>

    <?php // echo $lastQueryKey?>

<div id="filter-content" class="clear box1">
    
    <form id="carFormFilter" class="" action="" method="post">
        
        <div class="form-item">
            
            <label class="checkboxListLabel">
                <input id='secsSelMestre' onclick="checkbox.selMestre(this, 'secsItem')" 
                       type="checkbox" checked="" />Secretarias
            </label>
            
            <?php foreach ($secretarias as $secretaria) { ?>
            <div class='checkboxListItem'>
                <input class="secsItem" type="checkbox" 
                       value="<?php echo $secretaria['id']?>"
                       <?php echo array_search($secretaria['id'], $secs) !== false ? " checked='' " : ""?>
                       /> <?php echo $secretaria['nome']?>
            </div>
            <?php } ?>
        </div>
        
        <div class="clear">&nbsp;</div>
        
        <div class="form-item">
            
            <label class="checkboxListLabel">
                <input id='divsSelMestre' onclick="checkbox.selMestre(this, 'divsItem')" 
                       type="checkbox" checked=""/> Divisões
            </label>
                
            <?php foreach ($divisoes as $divisao) { ?>
            <div class='checkboxListItem'>
                <input class="divsItem" type="checkbox" 
                       value="<?php echo $divisao['id']?>"
                       <?php echo array_search($divisao['id'], $divs) !== false ? " checked='' " : ""?>
                       /> <?php echo $divisao['nome']?>
            </div>
            <?php } ?>
        </div>
        
        <div class="clear">&nbsp;</div>
        
        <div class="form-item">
            <label>Combustível</label>
            <select id="combustivel">
                <option value=""></option>
                <option value="Flex">Flex</option>
                <option value="Diesel">Diesel</option>
                <option value="Etanol">Etanol</option>
                <option value="Gasolina">Gasolina</option>
            </select>
        </div>

        <div class="clear">&nbsp;</div>
        
        <div class="form-item">
            <label>Buscar</label>
            <select id="buscarCol">
                <option value=""></option>
                <option value="placa" <?php echo $buscarCol == "placa" ? " selected ='' " : ""?> >Placa</option>
                <option value="cod"   <?php echo $buscarCol == "cod"   ? " selected ='' " : ""?> >Código</option>
                <option value="tag"   <?php echo $buscarCol == "tag"   ? " selected ='' " : ""?> >Tag</option>
            </select>
            <input type="text" id="buscar" value="<?php echo $buscar?>" placeholder=""/>
        </div>
        
        <div class="form-item">
            <label>Final da placa</label>
            <input type="text" id="finalPlaca" value="<?php echo $finalPlaca?>" placeholder=""/>
        </div>
        
        <div class="clear">&nbsp;</div>
        
        <div class="form-item">
            <label>&nbsp;</label>
            <input type="submit" value="OK"/>            
        </div>
    </form>
</div>

<div id="info-box">
    <strong>Num. registros: </strong> <?php echo $totNumRows?>
</div>

<div class="paginator clear">
    <?php for($p=0; $p<=$paginator->nPg; $p++){
        $class = $p == $paginator->pgCurrent ? 'sel' : '';
        ?><a class="<?php echo $class?> pgButton" data-pg="<?php echo $p?>" ><?php echo $p+1?></a><?php }?>
</div>  

<table id="carros" class="tabela2">
    <tr>
        <th>Secretaria</th>
        <th>Divisão</th>
        <th>Fabricante Modelo</th>
        <th>Tipo</th>
        <th>P.Livre</th>
        <th>Cota L</th>
        <th>Ab. Mês atual</th>
        <th>Ab. media</th>
        <th>Codigo</th>
        <th>Placa</th>
        <th></th>
    </tr>
    <?php foreach ($carros as $carro) { ?>
    <tr>
        <td><?php echo $carro['secretariaNome']?></td>
        <td><?php echo $carro['divisaoNome']?></td>
        <td><?php echo $carro['fabricanteNome']?> / <?php echo $carro['modeloNome']?></td>
        <td><?php echo $carro['carroTipo']?></td>
        <td><?php echo $carro['carroPasseLivre'] == 1 ? "&bull;" : ""?></td>  
        <td><?php echo $carro['carroCota']?></td>  
        <td><?php echo $carro['carroAbMesAtual']?></td>  
        <td><?php echo $carro['carroAbMediaKmLt']?></td>  
        <td><?php echo $carro['carroCodigo']?></td>
        <td><?php echo $carro['carroPlaca']?></td>
        <td>
            <div class="link1 fa-cog" onclick="location='carro/editar/id/<?php echo $carro['carroId']?>'"> Gerenciar</div>
        </td>
    </tr>
    <?php } ?>
</table>
