<!DOCTYPE HTML>
<html>
    <head>
        <?php require_once 'head.php'?>
        <link href="css/layout/painel.css" rel="stylesheet" type="text/css"/>
        
        <script src="js/layout/site.js" type="text/javascript"></script>
        <script src="ckeditor/ckeditor.js" type="text/javascript"></script>        
        
    </head>
    <body>
            <header>                
                <div id="bt-menu1" class="fa-bars" title="Menu" onclick="menu.setVisibilidade('menu1')"></div>
                <span id="app-nome">Sistema administrativo</span>
                <div id="usu-content" class="fa-user fa-caret-down-af"  onclick="menu.setVisibilidade('usu-menu')">
                    <span id="usu-nome"> <?php echo $this->obj->getUsuarioData('nome')?></span>
                    <div id="usu-menu">
                        <div class="fa-sign-out" onclick="location='usuario/sair'"> Sair</div>
                        <div class="fa-key" onclick="location='usuario/alterarPropriaSenha'"> Trocar senha</div>
                    </div>
                </div>
<!--                <div id="alertas-content">
                    <div id="alertas" class="fa-bell" onclick="menu.setVisibilidade('alertas-msgs')"></div>                
                </div>-->
            </header>
            <nav id="menu1" >
                <ul>
                    <li> 
                        <h2>
                            <span class="bt-exib fa-plus-square-o" data-subitens-vis="0"></span> 
                            <span class="controle-acesso"> Conteúdo</span> 
                        </h2>
                        <ul class="menu-subitens">
                            <li class="controle-acesso" onclick="location='texto/admListar'">Textos/Notícias</li>
                            <li class="controle-acesso" onclick="location='variavel/admListar'">Variáveis</li>
                            
                            <li class="controle-acesso" onclick="location='linha/admListar'">Categorias</li>
                            <li class="controle-acesso" onclick="location='produto/admListar'">Serviços</li>
                            
                            <li class="controle-acesso" onclick="location='imagem/admListar'">Imagens Galeria</li>
                            <li class="controle-acesso" onclick="location='slider/admListar'">Imagens Slider</li>
                            
                            <li class="controle-acesso" onclick="location='parceiro/admListar'">Parceiros</li>
                        </ul>                
                    </li>
                    <li>                    
                        <h2>
                            <span class="bt-exib fa-plus-square-o"  data-subitens-vis="0"></span>
                            Controle acesso
                        </h2>
                        <ul class="menu-subitens">
                            <li class="controle-acesso" onclick="location='usuario'">Usuários</li>                            
                            <li class="controle-acesso" onclick="location='usuarioGrupo'">Grupos</li>
                            <li class="controle-acesso" onclick="location='permissao'">Permissões</li>
                            <li class="controle-acesso" onclick="location='log'">Log</li>
                        </ul>                
                    </li>
                </ul>
            </nav>        
            <div id="content"><?php $this->content(0)?></div>
            <div id="msgError" class="msgError sysMsgBox"><?php echo FlashMsg::getMsgError()?></div>
            <div id="msgOk" class="msgOk sysMsgBox"><?php echo FlashMsg::getMsgOk()?></div>

            <!-- Configurações -->            
            <input id="files-url" type="hidden" value="<?php echo FILES_URL;?>"/>
            <input id="base-url" type="hidden" value="<?php echo BASE_URL;?>"/>
            <input id="controllers-permitidos" type="hidden" value="<?php echo $this->obj->getControllersPermitidos()?>"/>
            <div class="clear">&nbsp;</div>
        <?php echo $this->obj->headGetCss()?>
        <?php echo $this->obj->headGetJs()?>
    </body>
</html>