<?php $usuarioLogadoId = $this->obj->getUserData('id');?>
<!DOCTYPE HTML>
<html>
    <head>
        <?php require_once 'head.php'?>        
    </head>
    <body>
            <div id="msgError" class="msgError sysMsgBox"><?php echo FlashMsg::getMsgError()?></div>
            <div id="msgOk" class="msgOk sysMsgBox"><?php echo FlashMsg::getMsgOk()?></div>            
            <header>
                
                <div id="barra-usu">
                    <?php if(empty($usuarioLogadoId)){ ?>                        
                        <a class="fa-user" href="usuario/login"> Entrar</a>
                    <?php }else{ 
                        $uNome = $this->obj->getUserData('nome');
                        $uTipo = $this->obj->getUserData('super') == 1 ? "Super" : "Normal";
                        ?>    
                        Olá <?php echo $uNome ?>&nbsp;
                        (<?php echo $uTipo ?>)&nbsp;
                        <a class="fa-cog" href="usuario/sair" title="Configurações"></a>
                        <a class="fa-sign-out" href="usuario/sair" title="Sair"></a>
                    <?php } ?> 
                </div>
                                
                <img id="logo" src="img/logo.png" alt="Controle de combustíveis"/>
                
                <nav id="menu1" class="menu1" >                    
                    <ul>
                        <li onclick="location='index/index'">
                            <div class="menu-icone fa-home"></div>
                            <div class="menu-titulo">Home</div>
                        </li>
                        <li data-id-subitem="menu-subitem-1">
                            <div class="menu-icone fa-folder-open-o"></div>
                            <div class="menu-titulo">Cadastro</div>
                        </li>
                        <li data-id-subitem="menu-subitem-2">
                            <div class="menu-icone fa-cogs"></div>
                            <div class="menu-titulo">Adm</div>
                        </li>
                        <li data-id-subitem="menu-subitem-3">
                            <div class="menu-icone fa-car"></div>
                            <div class="menu-titulo">Abastecimento</div>
                        </li>
                    </ul>
                </nav> 
                
                <!-- menu subitens -->
                <nav id="menu1-subitens">
                    <ul id="menu-subitem-1">
                        <li  onclick="location='carro'">
                            <div class="menu-icone fa-car"></div>
                            <div class="menu-titulo">Veículo</div>
                        </li>   
                        <li  onclick="location='secretaria'">
                            <div class="menu-icone fa-building-o"></div>
                            <div class="menu-titulo">Secretarias</div>
                        </li>
                    </ul>
                
                    <ul id="menu-subitem-2">
                        <li onclick="location='permissao'">
                            <div class="menu-icone fa-key"></div>
                            <div class="menu-titulo">Permissões</div>
                        </li>  
                        <li onclick="location='usuarioGrupo'">
                            <div class="menu-icone fa-users"></div>
                            <div class="menu-titulo">Grupos de usuários</div>
                        </li>
                        <li onclick="location='usuario'">
                            <div class="menu-icone fa-user"></div>
                            <div class="menu-titulo">Usuários</div>
                        </li>
                    </ul>
                    
                    <ul id="menu-subitem-3">
<!--                        <li onclick="">
                            <div class="menu-icone fa-magic"></div>
                            <div class="menu-titulo">Abastecimento manual</div>
                        </li>  -->
                        <li onclick="location='abastecimento'">
                            <div class="menu-icone fa-list-ul"></div>
                            <div class="menu-titulo">Listar Abastecimentos</div>
                        </li>
                    </ul>                    
                    
                </nav> 
                
            </header>
                 
            <div id="content"><?php $this->content(0)?></div>
            <!-- Configurações -->            
            <input id="files-url" type="hidden" value="<?php echo FILES_URL;?>"/>
            <input id="base-url" type="hidden" value="<?php echo BASE_URL;?>"/>
            <div class="clear">&nbsp;</div>
            
            <?php echo $this->obj->headGetCss()?>
            <?php echo $this->obj->headGetJs()?>
            
        </div>
    </body>
</html>