<!--<link href="css/contato.css" rel="stylesheet" type="text/css"/>-->

<div id='contato'>
    <h1 class="titulo1">Contato</h1>  
    <form class="form1" action="contato/enviar" method="post">
        <div class="form-item">
            <label>Nome</label>
            <input type="text" name="Nome" />
        </div>    
        <div class="form-item">
            <label>E-mail</label>
            <input type="email" name="E-mail" required="" />
        </div>    
        <div class="form-item">
            <label>Mensagem</label>
            <textarea name="Mensagem"></textarea>
        </div>    
        <input class="botao1" type="submit" value="Enviar"/>
    </form>
    <div class="texto1">
<!--        <p><strong>Telefone:</strong> <?php echo $this->dados['telefone']?></p>-->
        <p><strong>E-mail:</strong> <?php echo $this->dados['email']?></p>
<!--        <p><strong>Endereço:</strong> <?php echo $this->dados['endereco']?> 
            &nbsp; <a class="link1" href="localizacao">Ver mapa</a>
        </p>-->
    </div>
</div>