<div class="painel-topo">
    <h1 class="fa-pencil"> Textos</h1>
    <div class="link1 fa-angle-double-left" onclick="location='texto/admListar'"> Voltar</div>
    <div class="link1 fa-plus-square" onclick="location='texto/admEditar'"> Novo</div>
</div>

<form action="texto/gravar" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="texto_id" value="<?php echo isset($this->dados['texto_id']) ? $this->dados['texto_id'] : 0?>" />        
    <div  class="form-item clear">
        <label>&nbsp;</label><?php echo isset($this->dados['created_at']) ? '<strong>Criado: </strong> ' . Date::toBr($this->dados['created_at']) : ''?>
        <?php echo isset($this->dados['updated_at']) ? '&nbsp;&nbsp; <strong>Atualizado: </strong> ' . Date::toBr($this->dados['updated_at']) : ''?>
    </div>
<!--    <div  class="form-item clear">
        <label>Ref</label>
        <input class="" type="text" name="texto_ref" placeholder="" value="<?php echo isset($this->dados['texto_ref']) ? $this->dados['texto_ref'] : ''?>" readonly=""/>        
    </div> -->
    <div  class="form-item clear">
        <label>Categoria</label>
        <select name="texto_cat">
            <option value="SISTEMA" <?php echo isset($this->dados['texto_cat']) 
                    && $this->dados['texto_cat'] == "SISTEMA" 
                    ? 'selected=""' : ''?> >Sistema</option>
            <option value="NOTICIA" <?php echo isset($this->dados['texto_cat']) 
                    && $this->dados['texto_cat'] == "NOTICIA" 
                    ? 'selected=""' : ''?> >Notícia</option>
            <option value="RODAPE" <?php echo isset($this->dados['texto_cat']) 
                    && $this->dados['texto_cat'] == "RODAPE" 
                    ? 'selected=""' : ''?> >Rodapé</option>
            <option value="HOME" <?php echo isset($this->dados['texto_cat']) 
                    && $this->dados['texto_cat'] == "HOME" 
                    ? 'selected=""' : ''?> >Página principal</option>
        </select>
    </div>    
    <div  class="form-item">
        <label>Título</label>
        <input class="" type="text" name="texto_titulo" placeholder="" value="<?php echo isset($this->dados['texto_titulo']) ? $this->dados['texto_titulo'] : ''?>"/>        
    </div>             
    <div class="form-item clear">
        <textarea id='editor' class="" name="texto_texto" placeholder=""><?php echo isset($this->dados['texto_texto']) ? $this->dados['texto_texto'] : ''?></textarea>        
    </div>    
    <div class='clear'>&nbsp;</div>
    <div id="arquivos" class="box1 galeria1">
        <h3>Arquivos</h3>
        <div class="form-item">
            <input class="form-file" type="file" name="anexo[]" multiple="">
        </div>
        <div class='clear'>&nbsp;</div>
        <?php
        if(isset($this->dados['arquivos'])){
            foreach ($this->dados['arquivos'] as $arquivo) {
                $arquivoUri = IMGS_PATH . "/" .$arquivo['arquivo_nome']; 
                ?>
                <div class="sel_item">                                    
                    <img class="thumbs1" src="<?php echo $arquivoUri?>" alt="<?php echo $arquivoUri?>"/>
                    <div class="item_apagar" href="" onclick="global.confirma('texto/apagarArquivo/arquivo_id/<?php echo $arquivo['arquivo_id']?>/texto_id/<?php echo $this->dados['texto_id']?>', '')">X</div>
                </div>
                <?php
            }
        }    
        ?>
    </div>    
    <div class="clear">&nbsp;</div>
    <input class="botao1" name="texto_gravar" type="submit" value="Gravar"/>   
    <div class="botao-apagar" onclick="global.confirma('texto/apagar/id/<?php echo isset($this->dados['texto_id']) ? $this->dados['texto_id'] : 0?>', '')">Apagar</div>  
</form>

<!-- CK Editor -->
<script src="adm/ckeditor/ckeditor.js" type="text/javascript"></script>        
<script> CKEDITOR.replace( 'editor' ); </script>

<script src="js/texto-form.js" type="text/javascript"></script>
<link href="css/texto-form.css" rel="stylesheet" type="text/css"/>