<h1 class="titulo1">Configurações</h1>
<form action="config/gravar" method="post">
    <div class="form-item">
        <label>Host</label>
        <input type="text" name="bdHost" value="<?php echo isset($bdHost) ? $bdHost : ''?>" required=""/>
    </div>    
    <div class="form-item">
        <label>Usuário do Banco</label>
        <input type="text" name="bdUsuario" value="<?php echo isset($bdUsuario) ? $bdUsuario : ''?>" required=""/>
    </div>    
    <div class="form-item">
        <label>Senha do Banco</label>
        <input type="text" name="bdSenha" value="<?php echo isset($bdSenha) ? $bdSenha : ''?>" required=""/>
    </div>    
    <div class="form-item">
        <label>Nome do Banco</label>
        <input type="text" name="bdNome" value="<?php echo isset($bdNome) ? $bdNome : ''?>" required=""/>
    </div>
    <div class="painel1">
        <input type="submit" value="Gravar"/>
    </div>    
</form>