<div class="painel-topo">
    <h1 class="fa-user"> Imagem</h1>
    <div class="link1 fa-angle-double-left" onclick="location='imagem/admListar'"> Voltar</div>    
</div>
<form action="imagem/gravar" method="post" enctype="multipart/form-data">
    <div class="form-item">
        <label>Selecione a imagem</label>
        <input type="file" name="img"/>
        <input type="submit" value="Enviar"/>    
    </div>
</form>