<h1 class="titulo1">Categoria</h1>
<form class="form-box" action="categoria/gravar" method="post" enctype="multipart/form-data">
    <div class="painel1">
        <div class="botao-menu2" onclick="location='categoria/admListar'">
            <img src="img/icons2/hand223.png" alt="Voltar"/>Voltar
        </div>
    </div>
    <input type="hidden" name="id" value="<?php echo isset($id) ? $id : ''?>"/>
    <div class="form-item">
        <label>Titulo</label>
        <input type="text" maxlength="300" name="titulo" 
               value="<?php echo isset($titulo) ? $titulo : ''?>"/>
    </div>    
    <div class="form-item">
        <label>&nbsp;</label>
        <input type="checkbox" name="destaque" value="1" 
            <?php echo isset($destaque) && $destaque == 1 ? 'checked=""' : ''?>/> 
            Destaque na pg principal
    </div>    
    <div class="form-item clear">
        <label>Descrição</label>
        <textarea id="editor" name="descricao"><?php echo isset($descricao) ? $descricao : ''?></textarea>
    </div>       
    <div class="form-item clear">
        <label>Imagem de capa</label>
        <input type="file" name="arq"/>
    </div>
    <div class="clear galeria1">
        <?php foreach ($imagens as $imagem){?>
            <div class="sel_item">
                <img class="thumbs1" src="files/<?php echo $imagem['arquivo_nome']?>" alt=""/>
                <div class="item_apagar" onclick="global.confirma('categoria/admApagarArq/arq-id/<?php echo $imagem['arquivo_id']?>/cat-id/<?php echo $id?>', '')" >X</div>
            </div>    
        <?php } ?>
    </div>
    <div class="painel1">
        <input type="submit" value="Gravar"/>
    </div>    
</form>
<!-- CK Editor -->
<script src="ckeditor/ckeditor.js" type="text/javascript"></script>        
<script> CKEDITOR.replace( 'editor' ); </script>