<table>
    <tr>
    <?php foreach ($colunasNomes as $colunaNome) { ?>    
        <th><?php echo urldecode($colunaNome)?></th>
    <?php } ?>
    </tr>
<?php foreach ($linhas as $linha) { ?>
    <tr>
    <?php foreach ($linha as $key => $coluna) { 
            if(is_numeric($key)){
                ?>
                <td><?php echo $coluna?></td>
                <?php 
            }
          } ?>
    </tr>
<?php } ?>
</table>

