<h1 class="titulo1">Grupo - criar/editar</h1>

<div class="painel1">
    <div class="link1 fa-angle-double-left" onclick="history.go(-1)"> Voltar</div>
</div>

<form id="usuarioForm" class="form1" action="usuarioGrupo/gravar" method="post" autocomplete="off">
    <input type="hidden" name="id" value="<?php echo isset($id) ? $id : '' ?>" />
    <div class="form-item">
        <label>Nome do Grupo</label>
        <input type="text" name="nome" required="" value="<?php echo isset($nome) ? $nome : '' ?>" autofocus=""/>
    </div> 
    <div class="clear">
        <input type="submit" value="Gravar"> 
    </div>
</form>