<h1 class="titulo1">Grupos de Usuários</h1>

<div class="painel1">
    <div class="link1 fa-plus-square" onclick="location='usuarioGrupo/editar'"> Novo</div>
</div>

<table class="tabela2">
    <tr>
        <th>Grupo</th>
        <th></th>
    </tr>
    <?php foreach ($grupos as $grupo):?> 
        <tr>
            <td><?php echo $grupo['nome']?></td>
            <td class="botoes">
                <div class="link1 fa-pencil" onclick="location='usuarioGrupo/editar/id/<?php echo $grupo['id'] ?>'"> Editar</div>
                &nbsp;&nbsp;
                <div class="link2 fa-times-circle" onclick="global.confirma('usuarioGrupo/apagar/id/<?php echo $grupo['id'] ?>')"> Apagar</div>
            </td>
        </tr>
    <?php endforeach;?>
</table>

