<link href="css/usuario/login.css" rel="stylesheet" type="text/css"/>
<form id="form-login" class="form-box" action="usuario/logar" method="post">          
    <h1 class="titulo1">Área restrita</h1>
    <div id="msgError" class="msgError"><?php echo FlashMsg::getMsgError()?></div>
        <div id="msgOk" class="msgOk"><?php echo FlashMsg::getMsgOk()?></div>
    <div class="form-item">
        <label>Usuário</label>
        <input type="text" name="usuario" value="" required=""  autofocus=""/>
    </div>              
    <div class="form-item clear">
        <label>Senha</label>
        <input type="password" name="senha" value="" onclick="this.value=''" required=""/>
    </div>
    <div class="painel1">
        <input type="submit" value="Entrar"/>        
    </div>
</form>