<h1 class="titulo1"> Cadastro</h1>

<div class="painel">
    <div class="link1 fa-angle-double-left" onclick="history.go(-1)"> Voltar</div>
</div>

<form id="usuarioForm" class="form1" action="usuario/gravar" method="post" autocomplete="off">
    <input type="hidden" name="id" value="0" />
    <div class="form-item">
        <label>Nome</label>
        <input type="text" name="nome" required="" value="<?php echo isset($nome) ? $nome : '' ?>"
               autofocus=""/>
    </div>
    <div class="form-item">
        <label>E-mail</label>
        <input type="email" name="email" required="" value="<?php echo isset($email) ? $email : '' ?>"/>
    </div>
    <div class="form-item">
        <label>Login</label>
        <input type="text" name="usuario" required="" value="<?php echo isset($usuario) ? $usuario : '' ?>"
               autofocus=""/>
    </div>   
    <div class="form-item">
        <label>Senha</label>
        <input type="password" name="senha" 
               placeholder="Mínimo 5 caracteres" value=""                               
               onclick="this.value=''"
               required=""
               minlength="5"
               />
        <!-- value tem que ter espaço para prevenir o autocomplete do navegador -->
    </div>    
    <div class="form-item">
        <label>Repita a senha</label>
        <input type="password" name="senha2" value="" 
               onclick="this.value=''"
               required="" 
               minlength="5"
               />
        
        <!-- value tem que ter espaço para prevenir o autocomplete do navegador -->
    </div> 
    <div class="painel">
        <input type="submit" value="Gravar"> 
    </div>
</form>