<h1 class="title">Usuários</h1>

<div class="painel1">
    <div class="link1 fa-plus-square" onclick="location='usuario/editar'"> Novo</div>
</div>

<table class="tabela2">
    <tr>
        <th>ID</th>
        <th>Usuário</th>
        <th>Grupos</th>
        <th>Super</th>
        <th></th>
    </tr>
    <?php foreach ($usuarios as $usuario):?> 
        <tr>
            <td><?php echo $usuario['id']?></td>
            <td><?php echo $usuario['nome']?> (<?php echo $usuario['usuario']?>)</td>
            <td>
                <?php foreach ($usuario['grupos'] as $key2 => $grupo):?> 
                    <?php echo $grupo['nome']?> <?php echo $key2 < count($usuario['grupos']) - 1 ? ", " : ""?>
                <?php endforeach;?>
            </td>
            <td><?php echo $usuario['super'] == 1 ? " &bull; " : ""?></td>
            <td class="botoes">
                <div class="link1 fa-pencil" onclick="location='usuario/editar/id/<?php echo $usuario['id'] ?>'"> Editar</div>
                &nbsp;&nbsp;
                <div class="link2 fa-times-circle" onclick="global.confirma('usuario/apagar/id/<?php echo $usuario['id'] ?>')"> Apagar</div>
            </td>
        </tr>
    <?php endforeach;?>
</table>

