<link href="css/global.css" rel="stylesheet" type="text/css"/>
<link href="css/usuario/login.css" rel="stylesheet" type="text/css"/>

<form id="form-login" class="form1" action="usuario/logar" method="post">          
    <h1 class="titulo1"><img id="logo" src="img/logo.png" alt=""/>Área restrita</h1>
    <div id="msgError" class="msgError"><?php echo FlashMsg::getMsgError()?></div>
        <div id="msgOk" class="msgOk"><?php echo FlashMsg::getMsgOk()?></div>
    <div class="form-item">
        <label>Login</label>
        <input type="text" name="usuario" value="" required=""  autofocus=""/>
    </div>              
    <div class="form-item clear">
        <label>Senha</label>
        <input type="password" name="senha" value="" onclick="this.value=''" required=""/>
    </div>
    <div class="form-item clear">
        <input type="submit" value="Entrar"/>    
        <!--<div class="link1 fa-heart" onclick="location='usuario/siteEditar'"> Cadastrar</div>-->
    </div>
</form>