<link href="css/texto/exibir.css" rel="stylesheet" type="text/css"/>
<h1 class="titulo1"><?php echo $texto_titulo?></h1>
<div id="texto-content" class="texto1">
    <div class="painel1">
        <div class="botao-voltar" onclick="history.go(-1)">
            <img src="img/icons2/hand223.png" alt="Voltar"/>Voltar
        </div>
    </div>
    <?php echo $texto_texto?>
</div>
<div class="social-plugins">
    <div class="fb-like" data-href="<?php echo URL::getUrl()?>" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>    
    <div class="fb-comments clear" data-href="<?php echo URL::getUrl()?>" data-numposts="5"></div>
</div>