<link href="css/texto/listar-global.css" rel="stylesheet" type="text/css"/>
<h1 class="titulo1"><?php echo isset($titulo) ? $titulo : 'Textos'?></h1>
<div id='noticias-content'>
    <div class="painel1">
        <div class="botao-menu2" onclick="history.go(-1)">
            <img src="img/icons2/hand223.png" alt="Voltar"/>
            Voltar
        </div>
    </div>
    <?php foreach ($textoLista as $textoItem): 
        $texto = strip_tags($textoItem['texto_texto']);
        $titulo = strip_tags($textoItem['texto_titulo']);
        $img = !empty($textoItem['capa']) ? "files/{$textoItem['capa']}" : "img/logo-mini.png";
        ?>        
        <div class="noticias-item texto1" onclick="location='texto/exibir/texto-id/<?php echo $textoItem['texto_id']?>'">
            <img class="noticias-item-capa" src="<?php echo $img?>" 
                 alt="<?php echo $titulo?>" title="<?php echo $titulo?>"/>
            <div class="noticias-item-texto">
                <h3><?php echo $titulo?></h3>
                <p>
                    <?php echo substr($texto, 0, 370)?> 
                    <?php echo strlen($texto) > 370 ? "..." : "" ?>
                </p>
            </div>
            <img class="noticias-item-bt" src="img/icons2/add13.png" alt="Leia mais" title="Leia mais"/>
        </div>
    <?php endforeach;?>
</div>

