<link href="css/secretaria/editar.css" rel="stylesheet" type="text/css"/>
<script src="js/secretaria/editar.js" type="text/javascript"></script>

<h1 class="titulo1">Secretaria</h1>

<div class="painel1">
    <div class="link1 fa-angle-double-left" onclick="location='secretaria'"> Voltar</div>
</div>

<section>
    
    <form id="editarForm" class="form1" action="secretaria/gravar" method="post">

        <input name="id" type="hidden" value="<?php echo isset($secretaria['id']) ? $secretaria['id'] : 0?>"/>

        <div class="form-item">
            <label>Data de cadastro</label>
            <input id="data" class="data" type="text" 
                   value="<?php echo isset($secretaria['created_at']) ? Date::toBr($secretaria['created_at']) : 0?>"/>
        </div>    

        <div class="form-item">
            <label>Nome</label>
            <input type="text" 
                   name="nome"
                   required=""
                   value="<?php echo isset($secretaria['nome']) ? $secretaria['nome'] : 0?>"/>
        </div>

        <div class="form-item clear">
            <input type="submit" value="Gravar"/>
        </div>

    </form>

</section>