<div class="painel-topo">
    <h1 class="fa-cog"> Variáveis</h1>
    <div class="link1 fa-angle-double-left" onclick="history.go(-1)"> Voltar</div>
</div>
<p class="aviso">
    <strong>ATENÇÂO!!! Muito cuidado ao alterar esses valores.</strong>
</p>
<table class="tabela1"> 
    <tr>
        <th>Nome</th>
        <th>Valor</th>
        <th>Ações</th>
    </tr>
    <?php foreach($this->dados['variaveis'] as $variavel): ?>
    <tr>
        <td><?php echo $variavel['variavel_nome']?></td>
        <td>
            <?php if($variavel['tipo'] == "booleano"){ ?>
                <?php echo $variavel['variavel_valor'] == 1 ? "Sim" : "Não"?>
            <?php }elseif($variavel['tipo'] == "cor"){ ?>
                <div class="cor-view" style="background-color:<?php echo $variavel['variavel_valor']?>"></div>
            <?php }else{ ?>
                <?php echo strip_tags($variavel['variavel_valor'])?>
            <?php } ?> 
        </td>    
        <td>
            <div class="link1 fa-pencil" 
                 onclick="location='variavel/admEditar/id/<?php echo $variavel['variavel_id']?>'">
                Editar</div>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

